In [ ]:
!pip install mp_api -q

Collecting mp_api
  Downloading mp_api-0.41.1-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.2/97.2 kB 5.3 MB/s eta 0:00:00
Collecting msgpack
  Downloading msgpack-1.0.8-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (385 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.1/385.1 kB 5.5 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: typing-extensions>=3.7.4.1 in /usr/local/lib/python3.9/dist-packages (from mp_api) (4.3.0)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.9/dist-packages (from mp_api) (2.28.1)
Collecting maggma>=0.57.1
  Downloading maggma-0.63.4-py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.0/118.0 kB 5.5 MB/s eta 0:00:00
Collecting monty>=2023.9.25
  Downloading monty-2024.2.26-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 4.7 MB/s eta 0:00:00
Collecting emmet-core>=0.78.0rc3
  Downloading emmet_core-0.78.7-py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.5/190.5 kB 6.6 MB/s eta 0:00:00
Collecting pymatgen!=2024.2.20,>=2022.3.7
  Downloading pymatgen-2024.3.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 5.5 MB/s eta 0:00:0000:010:01
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (from mp_api) (63.1.0)
Requirement already satisfied: smart-open in /usr/local/lib/python3.9/dist-packages (from mp_api) (5.2.1)
Collecting pybtex~=0.24
  Downloading pybtex-0.24.0-py2.py3-none-any.whl (561 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 561.4/561.4 kB 5.9 MB/s eta 0:00:00a 0:00:01
Collecting pydantic>=2.0
  Downloading pydantic-2.6.3-py3-none-any.whl (395 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.2/395.2 kB 4.5 MB/s eta 0:00:00a 0:00:01
Collecting pydantic-settings>=2.0
  Downloading pydantic_settings-2.2.1-py3-none-any.whl (13 kB)
Requirement already satisfied: jsonschema>=3.1.1 in /usr/local/lib/python3.9/dist-packages (from maggma>=0.57.1->mp_api) (4.7.2)
Requirement already satisfied: boto3>=1.20.41 in /usr/local/lib/python3.9/dist-packages (from maggma>=0.57.1->mp_api) (1.24.27)
Requirement already satisfied: tqdm>=4.19.6 in /usr/local/lib/python3.9/dist-packages (from maggma>=0.57.1->mp_api) (4.64.0)
Collecting dnspython>=1.16.0
  Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 4.7 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from maggma>=0.57.1->mp_api) (1.23.1)
Collecting orjson>=3.9.0
  Downloading orjson-3.9.15-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.4/138.4 kB 9.8 MB/s eta 0:00:00
Collecting pymongo>=4.2.0
  Downloading pymongo-4.6.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (676 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.5/676.5 kB 5.5 MB/s eta 0:00:00a 0:00:01
Collecting pyzmq>=24.0.1
  Downloading pyzmq-25.1.2-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 5.4 MB/s eta 0:00:00a 0:00:01
Collecting pydash>=4.1.0
  Downloading pydash-7.0.7-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.3/110.3 kB 2.6 MB/s eta 0:00:00a 0:00:01
Collecting uvicorn>=0.18.3
  Downloading uvicorn-0.27.1-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 6.6 MB/s eta 0:00:00
Collecting sshtunnel>=0.1.5
  Downloading sshtunnel-0.4.0-py2.py3-none-any.whl (24 kB)
Collecting fastapi>=0.42.0
  Downloading fastapi-0.110.0-py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.1/92.1 kB 7.6 MB/s eta 0:00:00
Collecting mongogrant>=0.3.1
  Downloading mongogrant-0.3.3-py3-none-any.whl (25 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.9/dist-packages (from maggma>=0.57.1->mp_api) (2.8.2)
Collecting mongomock>=3.10.0
  Downloading mongomock-4.1.2-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 10.8 MB/s eta 0:00:00
Collecting aioitertools>=0.5.1
  Downloading aioitertools-0.11.0-py3-none-any.whl (23 kB)
Collecting ruamel.yaml<0.18
  Downloading ruamel.yaml-0.17.40-py3-none-any.whl (113 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.7/113.7 kB 5.6 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (from pymatgen!=2024.2.20,>=2022.3.7->mp_api) (1.4.3)
Collecting palettable>=3.1.1
  Downloading palettable-3.3.3-py2.py3-none-any.whl (332 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.3/332.3 kB 4.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: joblib in /usr/local/lib/python3.9/dist-packages (from pymatgen!=2024.2.20,>=2022.3.7->mp_api) (1.1.0)
Collecting tabulate
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.9/dist-packages (from pymatgen!=2024.2.20,>=2022.3.7->mp_api) (2.8.4)
Requirement already satisfied: matplotlib>=1.5 in /usr/local/lib/python3.9/dist-packages (from pymatgen!=2024.2.20,>=2022.3.7->mp_api) (3.5.2)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.9/dist-packages (from pymatgen!=2024.2.20,>=2022.3.7->mp_api) (1.8.1)
Collecting spglib>=2.0.2
  Downloading spglib-2.3.1-cp39-cp39-manylinux_2_17_x86_64.whl (807 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.7/807.7 kB 6.5 MB/s eta 0:00:00a 0:00:01
Collecting plotly>=4.5.0
  Downloading plotly-5.19.0-py3-none-any.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 4.2 MB/s eta 0:00:0000:0100:01
Collecting uncertainties>=3.1.4
  Downloading uncertainties-3.1.7-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.4/98.4 kB 3.4 MB/s eta 0:00:00
Collecting sympy
  Downloading sympy-1.12-py3-none-any.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 5.6 MB/s eta 0:00:0000:0100:01
Collecting numpy>=1.17.3
  Downloading numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━ 17.1/18.2 MB 3.4 MB/s eta 0:00:01

In [54]:
import pandas as pd
import numpy as np

import sys
sys.path.append('/notebooks/src/')

from Ranker import *

ModuleNotFoundError: No module named 'mp_api'

# Read in all materials and take only flat ones

In [34]:
df = pd.read_csv("csv_data/material_flatness_score_data/Compound_flatness_score_segments.csv")

In [35]:
df_slice = df[['material_id','flat','flat_segments']]
# extract materials with at least one flat band across the whole k-space path chosen
df_flat_only = df_slice.loc[df_slice['Flat/not-flat']==True]
df_flat_only

            MP-ID  Flat/not-flat Flat segments
4            mp-7           True           [4]
18          mp-25           True           [3]
26          mp-35           True  [1, 2, 3, 4]
33          mp-43           True  [1, 2, 3, 4]
64          mp-83           True        [3, 4]
...           ...            ...           ...
69787  mp-1443188           True           [4]
69788  mp-1443279           True     [1, 3, 4]
69791  mp-1443442           True        [3, 4]
69806  mp-1445771           True  [1, 2, 3, 4]
69816  mp-1475733           True     [1, 2, 4]

[33399 rows x 3 columns]

# Add synthNN scores

In [36]:
df_synthNN_scores = pd.read_csv("csv_data/SynthNN_final_scores.csv")
df_synthNN_scores

            mp-ID       Formula  SynthNN_score
0            mp-7             S       0.013924
1           mp-25            N2       0.127548
2           mp-35            Mn       0.007099
3           mp-43             U       0.001247
4           mp-83             S       0.013924
...           ...           ...            ...
33394  mp-1443188        ZnCuF4       0.574649
33395  mp-1443279       Cr(OF)3       0.035679
33396  mp-1443442           VF5       0.727455
33397  mp-1445771      K2P2H2O7       0.974588
33398  mp-1475733  PdAu2(NCl2)4       0.010389

[33399 rows x 3 columns]

In [37]:
df_flat_only['Formula']= df_synthNN_scores['Formula'].values
df_flat_only['SynthNN_score']= df_synthNN_scores['SynthNN_score'].values
df_flat_only

/tmp/ipykernel_549/1011652856.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_flat_only['Formula']= df_synthNN_scores['Formula'].values
/tmp/ipykernel_549/1011652856.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_flat_only['SynthNN_score']= df_synthNN_scores['SynthNN_score'].values

            MP-ID  Flat/not-flat Flat segments       Formula  SynthNN_score
4            mp-7           True           [4]             S       0.013924
18          mp-25           True           [3]            N2       0.127548
26          mp-35           True  [1, 2, 3, 4]            Mn       0.007099
33          mp-43           True  [1, 2, 3, 4]             U       0.001247
64          mp-83           True        [3, 4]             S       0.013924
...           ...            ...           ...           ...            ...
69787  mp-1443188           True           [4]        ZnCuF4       0.574649
69788  mp-1443279           True     [1, 3, 4]       Cr(OF)3       0.035679
69791  mp-1443442           True        [3, 4]           VF5       0.727455
69806  mp-1445771           True  [1, 2, 3, 4]      K2P2H2O7       0.974588
69816  mp-1475733           True     [1, 2, 4]  PdAu2(NCl2)4       0.010389

[33399 rows x 5 columns]

# Add sublattice elements 
### **Note at this point, we cut out rows from the 33399 array to match the smaller 33251 array which was actually clustered
### When adding e.g. CNN_synth scores, we will need to add it above, before this cut is made, so that all rows match up

In [38]:
df_sublattices = pd.read_csv("csv_data/material_flatness_score_data/Flat_band_sublattices.csv")
df_sublattices.rename(columns={'MP_index': 'MP-ID'}, inplace=True)
df_sublattices.drop(columns=['Unnamed: 0'], inplace=True)

In [39]:
merged_df = pd.merge(df_flat_only, df_sublattices, on='MP-ID', how='inner')
merged_df

,MP-ID,Flat/not-flat,Flat segments,Formula,SynthNN_score,Cluster_ID,cluster_size,sublattice_element,dbcv_cluster,probabilities
0,mp-7,True,[4],S,0.013924,-1,24875,S,0.846820,0.000000
1,mp-25,True,[3],N2,0.127548,63,282,N,0.212178,0.104165
2,mp-35,True,"[1, 2, 3, 4]",Mn,0.007099,-1,24875,Mn,0.846820,0.000000
3,mp-43,True,"[1, 2, 3, 4]",U,0.001247,-1,24875,U,0.846820,0.000000
4,mp-83,True,"[3, 4]",S,0.013924,38,22,S,0.468464,0.972129
...,...,...,...,...,...,...,...,...,...,...
33246,mp-1443188,True,[4],ZnCuF4,0.574649,-1,24875,Cu,0.846820,0.000000
33247,mp-1443279,True,"[1, 3, 4]",Cr(OF)3,0.035679,-1,24875,F,0.846820,0.000000
33248,mp-1443442,True,"[3, 4]",VF5,0.727455,-1,24875,F,0.846820,0.000000
33249,mp-1445771,True,"[1, 2, 3, 4]",K2P2H2O7,0.974588,-1,24875,O,0.846820,0.000000
33250,mp-1475733,True,"[1, 2, 4]",PdAu2(NCl2)4,0.010389,-1,24875,N,0.846820,0.000000

# Add materials project information